allow-lan: true
ipv6: true
log-level: error
mode: rule
port: 7890
socks-port: 7891
proxies:
#+- { name: SHADOWSOCKS_WSS, server: demo.zhijie.online, port: 443, type: ss, cipher: chacha20-ietf-poly1305, password: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, plugin: v2ray-plugin, plugin-opts: { header: { Host: demo.zhijie.online }, host: demo.zhijie.online, mode: websocket, skip-cert-verify: true, tls: true, path: /wss-shadowsocks } }
#(- { name: TROJAN_GRPC, server: demo.zhijie.online, port: 443, type: trojan, network: grpc, password: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, skip-cert-verify: true, sni: demo.zhijie.online, udp: true, grpc-opts: { grpc-service-name: gRPCTROJAN } }
#)- { name: TROJAN_WSS, server: demo.zhijie.online, port: 443, type: trojan, network: ws, password: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, skip-cert-verify: true, sni: demo.zhijie.online, udp: true, ws-opts: { headers: { Host: demo.zhijie.online }, path: /wss-trojan } }
##- { name: VMESS_GRPC, server: demo.zhijie.online, port: 443, type: vmess, alterId: 0, cipher: auto, network: grpc, servername: demo.zhijie.online, skip-cert-verify: true, tls: true, udp: true, uuid: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, grpc-opts: { grpc-service-name: gRPCVMESS } }
  - { name: VMESS_WSS, server: demo.zhijie.online, port: 443, type: vmess, alterId: 0, cipher: auto, network: ws, servername: demo.zhijie.online, skip-cert-verify: true, tls: true, udp: true, uuid: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, ws-opts: { headers: { Host: demo.zhijie.online }, path: /wss-vmess } }
proxy-groups:
  - {name: PROXY, interval: 75, proxies: [VMESS_WSS], type: fallback, url: 'https://cp.cloudflare.com'}
rules:
  - GEOIP,CN,DIRECT
  - IP-CIDR,0.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.0.0.0/24,DIRECT
  - IP-CIDR,192.0.2.0/24,DIRECT
  - IP-CIDR,192.31.196.0/24,DIRECT
  - IP-CIDR,192.52.193.0/24,DIRECT
  - IP-CIDR,192.88.99.0/24,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,192.175.48.0/24,DIRECT
  - IP-CIDR,198.18.0.0/15,DIRECT
  - IP-CIDR,198.51.100.0/24,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,240.0.0.0/4,DIRECT
  - IP-CIDR6,::/127,DIRECT
  - IP-CIDR6,64:ff9b::/96,DIRECT
  - IP-CIDR6,64:ff9b:1::/48,DIRECT
  - IP-CIDR6,100::/64,DIRECT
  - IP-CIDR6,2001::/23,DIRECT
  - IP-CIDR6,2001:db8::/32,DIRECT
  - IP-CIDR6,2002::/16,DIRECT
  - IP-CIDR6,2620:4f:8000::/48,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - MATCH,PROXY
