allow-lan: true
log-level: error
mixed-port: 7890
ipv6: true
mode: rule
proxy-groups:
proxy-providers:
rules:
  - IP-CIDR,0.0.0.0/32,DIRECT
  - IP-CIDR,0.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.0.0.0/24,DIRECT
  - IP-CIDR,192.0.0.0/29,DIRECT
  - IP-CIDR,192.0.0.10/32,DIRECT
  - IP-CIDR,192.0.0.170/32,DIRECT
  - IP-CIDR,192.0.0.171/32,DIRECT
  - IP-CIDR,192.0.0.8/32,DIRECT
  - IP-CIDR,192.0.0.9/32,DIRECT
  - IP-CIDR,192.0.2.0/24,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,192.175.48.0/24,DIRECT
  - IP-CIDR,192.31.196.0/24,DIRECT
  - IP-CIDR,192.52.193.0/24,DIRECT
  - IP-CIDR,192.88.99.0/24,DIRECT
  - IP-CIDR,198.18.0.0/15,DIRECT
  - IP-CIDR,198.51.100.0/24,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,240.0.0.0/4,DIRECT
  - IP-CIDR,255.255.255.255/32,DIRECT
  - IP-CIDR6,100::/64,DIRECT
  - IP-CIDR6,2001:10::/28,DIRECT
  - IP-CIDR6,2001:1::1/128,DIRECT
  - IP-CIDR6,2001:1::2/128,DIRECT
  - IP-CIDR6,2001:20::/28,DIRECT
  - IP-CIDR6,2001::/23,DIRECT
  - IP-CIDR6,2001:2::/48,DIRECT
  - IP-CIDR6,2001::/32,DIRECT
  - IP-CIDR6,2001:3::/32,DIRECT
  - IP-CIDR6,2001:4:112::/48,DIRECT
  - IP-CIDR6,2001:db8::/32,DIRECT
  - IP-CIDR6,2002::/16,DIRECT
  - IP-CIDR6,2620:4f:8000::/48,DIRECT
  - IP-CIDR6,64:ff9b:1::/48,DIRECT
  - IP-CIDR6,64:ff9b::/96,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - IP-CIDR6,::/128,DIRECT
  - IP-CIDR6,::1/128,DIRECT
  - IP-CIDR6,::ffff:0:0/96,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
