allow-lan: true
ipv6: true
log-level: error
mixed-port: 7890
mode: rule
proxies:
  - { name: VLESS_GRPC, server: demo.zhijie.online, port: 443, type: vless, network: grpc, skip-cert-verify: true, tls: true, udp: true, uuid: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, grpc-opts: { grpc-service-name: gRPC.VLESS } }
  - { name: VLESS_WSS, server: demo.zhijie.online, port: 443, type: vless, network: ws, skip-cert-verify: true, tls: true, udp: true, uuid: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, ws-opts: { headers: { Host: demo.zhijie.online }, path: /wss-vless } }
  - { name: VMESS_GRPC, server: demo.zhijie.online, port: 443, type: vmess, alterId: 0, cipher: auto, network: grpc, skip-cert-verify: true, tls: true, udp: true, uuid: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, grpc-opts: { grpc-service-name: gRPC.VMESS } }
  - { name: VMESS_WSS, server: demo.zhijie.online, port: 443, type: vmess, alterId: 0, cipher: auto, network: ws, skip-cert-verify: true, tls: true, udp: true, uuid: 99235a6e-05d4-2afe-2990-5bc5cf1f5c52, ws-opts: { headers: { Host: demo.zhijie.online }, path: /wss-vmess } }
proxy-groups:
  - {name: PROXY, interval: 75, proxies: [GRPC, WSS], type: url-test, url: 'https://www.google.com/generate_204'}
  - {name: GRPC, interval: 150, proxies: [VLESS_GRPC, VMESS_GRPC], type: fallback, url: 'https://www.google.com/generate_204'}
  - {name: WSS, interval: 150, proxies: [VLESS_WSS, VMESS_WSS], type: fallback, url: 'https://www.google.com/generate_204'}
rules:
  - GEOIP,CN,DIRECT
  - IP-CIDR,0.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.0.0.0/24,DIRECT
  - IP-CIDR,192.0.2.0/24,DIRECT
  - IP-CIDR,192.31.196.0/24,DIRECT
  - IP-CIDR,192.52.193.0/24,DIRECT
  - IP-CIDR,192.88.99.0/24,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,192.175.48.0/24,DIRECT
  - IP-CIDR,198.18.0.0/15,DIRECT
  - IP-CIDR,198.51.100.0/24,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,240.0.0.0/4,DIRECT
  - IP-CIDR6,::/127,DIRECT
  - IP-CIDR6,64:ff9b::/96,DIRECT
  - IP-CIDR6,64:ff9b:1::/48,DIRECT
  - IP-CIDR6,100::/64,DIRECT
  - IP-CIDR6,2001::/23,DIRECT
  - IP-CIDR6,2001:db8::/32,DIRECT
  - IP-CIDR6,2002::/16,DIRECT
  - IP-CIDR6,2620:4f:8000::/48,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - MATCH,PROXY
