log:
  level: error
  production: true
plugins:
  - tag: forward_query_to_recursive_dns
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'tcp://localhost'
          dial_addr: '127.0.0.1:5335'
          enable_pipeline: true
        - addr: 'udp://localhost'
          dial_addr: '127.0.0.1:5335'
        - addr: 'https://localhost/dns-query'
          dial_addr: '127.0.0.1:5333'
          enable_http3: false
          insecure_skip_verify: true
        - addr: 'tls://localhost'
          dial_addr: '127.0.0.1:5355'
          enable_pipeline: true
          insecure_skip_verify: true
  - tag: forward_query_to_local_ecs_doh_ipv4
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '101.226.4.6:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '123.125.81.6:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '140.207.198.6:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '218.30.118.6:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.5.5.5:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://dns.ipv6dns.com/dns-query'
          dial_addr: '221.228.217.28:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '1.12.12.12:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '120.53.53.53:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://sm2.doh.pub/dns-query'
          dial_addr: '106.55.91.174:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_ecs_doh_ipv6
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '[2400:3200::1]:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '[2400:3200:baba::1]:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://dns.ipv6dns.com/dns-query'
          dial_addr: '[240e:e9:900b::5]:443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_ecs_dot_ipv4
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'tls://dot.360.cn'
          dial_addr: '101.226.4.6:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dot.360.cn'
          dial_addr: '123.125.81.6:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dot.360.cn'
          dial_addr: '140.207.198.6:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dot.360.cn'
          dial_addr: '218.30.118.6:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_ecs_dot_ipv6
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200::1]:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200:baba::1]:853'
          enable_pipeline: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dns.ipv6dns.com'
          dial_addr: '[240e:e9:900b::5]:853'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_no_ecs_doh_ipv4
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://doh-pure.onedns.net/dns-query'
          dial_addr: '54.223.159.81:443'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'https://dns.tuna.tsinghua.edu.cn/dns-query'
          dial_addr: '101.6.6.6:8443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_no_ecs_doh_ipv6
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://dns.tuna.tsinghua.edu.cn/dns-query'
          dial_addr: '[2402:f000:1:416:101:6:6:6]:8443'
          enable_http3: false
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_no_ecs_dot_ipv4
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'tls://dot-pure.onedns.net'
          dial_addr: '54.223.159.81:853'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
        - addr: 'tls://dns.tuna.tsinghua.edu.cn'
          dial_addr: '101.6.6.6:8853'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
  - tag: forward_query_to_local_no_ecs_dot_ipv6
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'tls://dns.tuna.tsinghua.edu.cn'
          dial_addr: '[2402:f000:1:416:101:6:6:6]:8853'
          enable_pipeline: true
          insecure_skip_verify: true
#+        socks5: '127.0.0.1:7890'
